/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.


var awsmobile = {
    "aws_project_region": "us-east-2"
};


export default awsmobile;

